version: "3.9"

services:
#  backend:
#    build: .
#    container_name: capstone_backend
#    ports:
#      - "8000:8000"
#    volumes:
#      - ./mydb.sqlite3:/app/mydb.sqlite3  # persist SQLite DB


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
